import { Track, ArtistResult } from "@/types";

const SPOTIFY_API = "https://api.spotify.com/v1";
const TOKEN_URL = "https://accounts.spotify.com/api/token";

// --- Client Credentials (server-side, no user login needed) ---

let clientToken: string | null = null;
let clientTokenExpiry = 0;

async function getClientToken(): Promise<string> {
  if (clientToken && Date.now() < clientTokenExpiry) return clientToken;

  const res = await fetch(TOKEN_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Authorization: `Basic ${Buffer.from(
        `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`
      ).toString("base64")}`,
    },
    body: "grant_type=client_credentials",
  });

  if (!res.ok) {
    const errText = await res.text();
    console.error(`Spotify token error: ${res.status} - ${errText}`);
    throw new Error(`Failed to get Spotify client token: ${res.status}`);
  }
  const data = await res.json();
  clientToken = data.access_token;
  clientTokenExpiry = Date.now() + (data.expires_in - 60) * 1000;
  return clientToken!;
}

async function spotifyFetch(path: string, token?: string) {
  const t = token || (await getClientToken());
  const res = await fetch(`${SPOTIFY_API}${path}`, {
    headers: { Authorization: `Bearer ${t}` },
  });
  if (res.status === 429) {
    const retryAfter = parseInt(res.headers.get("Retry-After") || "2", 10);
    await new Promise((r) => setTimeout(r, retryAfter * 1000));
    return spotifyFetch(path, token);
  }
  if (!res.ok) {
    const errText = await res.text();
    console.error(`Spotify API error: ${res.status} on ${path} - ${errText}`);
    throw new Error(`Spotify API error: ${res.status} on ${path}`);
  }
  return res.json();
}

// --- Search & Top Tracks ---

export async function searchArtist(
  name: string
): Promise<{ id: string; name: string; imageUrl: string } | null> {
  const data = await spotifyFetch(
    `/search?q=${encodeURIComponent(name)}&type=artist&limit=1`
  );
  const artist = data.artists?.items?.[0];
  if (!artist) return null;
  return {
    id: artist.id,
    name: artist.name,
    imageUrl: artist.images?.[0]?.url || "",
  };
}

export async function getTopTracks(
  artistId: string,
  market = "US"
): Promise<Track[]> {
  const data = await spotifyFetch(
    `/artists/${artistId}/top-tracks?market=${market}`
  );
  // Fetch all available top tracks (up to 10 from Spotify API)
  return (data.tracks || []).map(
    (t: {
      id: string;
      name: string;
      popularity: number;
      artists: { name: string }[];
      album: { name: string; images: { url: string }[] };
      preview_url: string | null;
      uri: string;
      duration_ms: number;
    }) => ({
      id: t.id,
      name: t.name,
      artist: t.artists[0]?.name || "",
      albumName: t.album.name,
      albumArt: t.album.images?.[0]?.url || "",
      previewUrl: t.preview_url,
      spotifyUri: t.uri,
      durationMs: t.duration_ms,
      popularity: t.popularity ?? 0,
    })
  );
}

export async function getArtistTracks(
  artistName: string
): Promise<ArtistResult> {
  const artist = await searchArtist(artistName);
  if (!artist) {
    return { name: artistName, found: false, tracks: [] };
  }
  const tracks = await getTopTracks(artist.id);
  return {
    name: artist.name,
    found: true,
    spotifyId: artist.id,
    imageUrl: artist.imageUrl,
    tracks,
  };
}

// Batch fetch with rate-limit-friendly delays
export async function batchGetArtistTracks(
  artists: string[],
  onProgress?: (done: number, total: number) => void
): Promise<ArtistResult[]> {
  const results: ArtistResult[] = [];
  for (let i = 0; i < artists.length; i++) {
    results.push(await getArtistTracks(artists[i]));
    onProgress?.(i + 1, artists.length);
    // Small delay to stay under rate limits
    if (i < artists.length - 1) {
      await new Promise((r) => setTimeout(r, 100));
    }
  }
  return results;
}

// --- Playlist Creation (requires user access token) ---

export async function createSpotifyPlaylist(
  accessToken: string,
  userId: string,
  name: string,
  trackUris: string[]
): Promise<{ playlistUrl: string; playlistId: string }> {
  // Create playlist
  const createRes = await fetch(`${SPOTIFY_API}/users/${userId}/playlists`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      name,
      description: `Generated by Festival Playlist Generator`,
      public: true,
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.text();
    throw new Error(`Failed to create playlist: ${err}`);
  }

  const playlist = await createRes.json();

  // Deduplicate track URIs
  const uniqueUris = [...new Set(trackUris)];

  // Add tracks in batches of 100 (Spotify limit)
  for (let i = 0; i < uniqueUris.length; i += 100) {
    const batch = uniqueUris.slice(i, i + 100);
    const addRes = await fetch(
      `${SPOTIFY_API}/playlists/${playlist.id}/tracks`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ uris: batch }),
      }
    );
    if (!addRes.ok) {
      console.error(`Failed to add tracks batch ${i}: ${await addRes.text()}`);
    }
  }

  return {
    playlistUrl: playlist.external_urls.spotify,
    playlistId: playlist.id,
  };
}

// Get current user profile
export async function getSpotifyUser(
  accessToken: string
): Promise<{ id: string; displayName: string }> {
  const res = await fetch(`${SPOTIFY_API}/me`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) throw new Error("Failed to get Spotify user");
  const data = await res.json();
  return { id: data.id, displayName: data.display_name || data.id };
}
