const YT_API = "https://www.googleapis.com/youtube/v3";

interface VideoSearchResult {
  videoId: string;
  title: string;
  thumbnail: string;
}

// Search for a music video
export async function searchVideo(
  songTitle: string,
  artistName: string,
  accessToken: string
): Promise<VideoSearchResult | null> {
  const query = `${artistName} ${songTitle} official music video`;
  const res = await fetch(
    `${YT_API}/search?part=snippet&q=${encodeURIComponent(
      query
    )}&type=video&videoCategoryId=10&maxResults=1`,
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );

  if (!res.ok) {
    if (res.status === 403) {
      throw new Error("QUOTA_EXCEEDED");
    }
    throw new Error(`YouTube search failed: ${res.status}`);
  }

  const data = await res.json();
  const item = data.items?.[0];
  if (!item) return null;

  return {
    videoId: item.id.videoId,
    title: item.snippet.title,
    thumbnail: item.snippet.thumbnails?.default?.url || "",
  };
}

// Create a YouTube playlist
export async function createYouTubePlaylist(
  accessToken: string,
  title: string,
  description: string
): Promise<string> {
  const res = await fetch(`${YT_API}/playlists?part=snippet,status`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      snippet: { title, description },
      status: { privacyStatus: "public" },
    }),
  });

  if (!res.ok) throw new Error(`Failed to create YouTube playlist: ${res.status}`);
  const data = await res.json();
  return data.id;
}

// Add a video to a playlist
async function addVideoToPlaylist(
  accessToken: string,
  playlistId: string,
  videoId: string
): Promise<boolean> {
  const res = await fetch(`${YT_API}/playlistItems?part=snippet`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      snippet: {
        playlistId,
        resourceId: { kind: "youtube#video", videoId },
      },
    }),
  });
  return res.ok;
}

// Full flow: search videos + create playlist
export async function createYouTubePlaylistFromTracks(
  accessToken: string,
  playlistTitle: string,
  tracks: { name: string; artist: string }[]
): Promise<{
  playlistUrl: string;
  playlistId: string;
  added: number;
  skipped: string[];
}> {
  const playlistId = await createYouTubePlaylist(
    accessToken,
    playlistTitle,
    "Generated by Festival Playlist Generator"
  );

  const skipped: string[] = [];
  let added = 0;

  for (const track of tracks) {
    try {
      const video = await searchVideo(track.name, track.artist, accessToken);
      if (video) {
        const success = await addVideoToPlaylist(accessToken, playlistId, video.videoId);
        if (success) added++;
        else skipped.push(`${track.artist} - ${track.name}`);
      } else {
        skipped.push(`${track.artist} - ${track.name}`);
      }
      // Delay to be gentle with quota
      await new Promise((r) => setTimeout(r, 200));
    } catch (err) {
      if (err instanceof Error && err.message === "QUOTA_EXCEEDED") {
        // Stop early, return what we have
        skipped.push(
          ...tracks
            .slice(tracks.indexOf(track))
            .map((t) => `${t.artist} - ${t.name}`)
        );
        break;
      }
      skipped.push(`${track.artist} - ${track.name}`);
    }
  }

  return {
    playlistUrl: `https://www.youtube.com/playlist?list=${playlistId}`,
    playlistId,
    added,
    skipped,
  };
}
